name: Fetch and Compress JSON Data

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  fetch-compress-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      -  uses: actions/checkout@v2
      -  uses: actions/setup-node@v2
          with: 
            node-version: 18

    - name: Fetch JSON data
      run: |
        curl -o data.json "https://ap-south-1.aws.data.mongodb-api.com/app/blue-splash-kurxzvd/endpoint/products"

    - name: Compress JSON data
      run: |
        gzip data.json

    - name: Upload compressed file
      uses: actions/upload-artifact@v2
      with:
        name: data.json.gz
        path: data.json.gz